# coding: utf-8

"""
    Yanshee RESTful API

    Yanshee RESTful APIs是一套专门为编程爱好者提供二次开发的接口．它通过http/https的方式向外界提供机器人控制，传感器读取，机器人视觉等功能．用户还可以通过编程的方式训练自己的模型，学习一些机器学习的内容．  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: swenggroup@ubtrobot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest
from pprint import pprint

import openadk
from openadk.models.visions_stream import VisionsStream  # noqa: E501
from openadk.rest import ApiException


class TestVisionsStream(unittest.TestCase):
    """VisionsStream unit test stubs"""

    def setUp(self):
        self.configuration = openadk.Configuration()
        self.configuration.host = 'http://10.10.60.196:9090/v1'
        self.api_instance = openadk.api.visions_api.VisionsApi(openadk.ApiClient(self.configuration))  # noqa: E501
        pass

    def tearDown(self):
        pass

    def testVisionsStream(self):
        """Test VisionsStream"""
        # FIXME: construct object with mandatory attributes with example values
        body = openadk.VisionsStream(resolution='640x480')  # VisionsStream |  (optional)

        for i in range(100):
            try:
                # 打开摄像头的视频流
                api_response = self.api_instance.post_visions_streams(body=body)
                pprint(api_response)
            except ApiException as e:
                print("Exception when calling VisionsApi->post_visions_streams: %s\n" % e)

            try:
                # 关闭摄像头的视频流
                api_response = self.api_instance.delete_visions_streams()
                pprint(api_response)
            except ApiException as e:
                print("Exception when calling VisionsApi->delete_visions_streams: %s\n" % e)


if __name__ == '__main__':
    unittest.main()
