# coding: utf-8

"""
    Yanshee RESTful API

     ## Overview Yanshee RESTful APIs are generated by the [swagger-codegen](https://github.com/swagger-api/swagger-codegen) project. By using the [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki) from a remote server. The API service uses the [Connexion](https://github.com/zalando/connexion) library on top of Flask.  To provide the API service, Yanshee RESTful APIs are integrated into apollo package, it is a part of Yanshee-ROS framework. Yanshee RESTful APIs provided two language versions: - [English version](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [Chinese version](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## Requirements. Python 2.7 or 3.4+  ## Getting Started Please follow the [installation procedure](#installation--usage) and then run the following:  ``` from __future__ import print_function import time import openadk from openadk.rest import ApiException from pprint import pprint  # create an instance of the API class configuration = openadk.Configuration() configuration.host = 'http://192.168.1.100:9090/v1' api_instance = openadk.DevicesApi(openadk.ApiClient(configuration)) try:  # Get system's battery information  api_response = api_instance.get_devices_battery()  pprint(api_response) except ApiException as e:  print(\"Exception when calling DevicesApi->get_devices_battery: %s\" % e)  ```   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: swenggroup@ubtrobot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openadk
from openadk.api.motions_api import MotionsApi  # noqa: E501
from openadk.rest import ApiException
from openadk.models.motions_parameter import MotionsParameter  # noqa: F401,E501
import time

class TestMotionsApi(unittest.TestCase):
    """MotionsApi unit test stubs"""

    def setUp(self):
        self.configuration = openadk.Configuration()
        self.configuration.host = 'http://10.10.69.146:9090/v1'
        self.api_instance = openadk.api.motions_api.MotionsApi(openadk.ApiClient(self.configuration))  # noqa: E501
    def tearDown(self):
        pass

    def test_delete_motions_music(self):
        """Test case for delete_motions_music

        Delete motion files  # noqa: E501
        """
        body = openadk.Name('test_motion')  # Name | 动作文件名
        try:
            # 删除动作文件（只能删除用户上传的文件）
            api_response = self.api_instance.delete_motions_music(body)
            print(api_response)
            self.assertIn(api_response.code, (0, 103))
        except ApiException as e:
            print("Exception when calling MotionsApi->delete_motions_music: %s\n" % e)

    def test_get_motions(self):
        """Test case for get_motions

        Get the current motions' status  # noqa: E501
        """
        try:
            # 获取当前的运动状态
            api_response = self.api_instance.get_motions()
            print(api_response)
            self.assertEqual(0, api_response.code)
        except ApiException as e:
            print("Exception when calling MotionsApi->get_motions: %s\n" % e)

    def test_get_motions_list(self):
        """Test case for get_motions_list

        Get all the motions' name  # noqa: E501
        """
        try:
            # 获取动作列表
            api_response = self.api_instance.get_motions_list()
            print(api_response)
            self.assertEqual(0, api_response.code)
            self.assertNotEqual(None, api_response.data)
        except ApiException as e:
            print("Exception when calling MotionsApi->get_motions_list: %s\n" % e)

    def test_post_motions(self):
        """Test case for post_motions

        Upload motion files  # noqa: E501
        """
        for name in ['test_motion.hts', 'test_motion.mp3', 'test_motion.zip']:
            file = 'res_motions/'+name  # file | 上传文件
            try:
                # 上传动作文件
                api_response = self.api_instance.post_motions(file)
                print(api_response)
                if file.endswith('hts') or file.endswith('zip'):
                    self.assertEqual(0, api_response.code)
                else:
                    self.assertEqual(104, api_response.code)
            except ApiException as e:
                print("Exception when calling MotionsApi->post_motions: %s\n" % e)

    def test_put_motions(self):
        """Test case for put_motions

        Update the motions  # noqa: E501
        """
        motion = MotionsParameter(name='wave', direction='both', speed='fast', repeat=2)
        for operation in ['start', 'pause', 'resume', 'stop']:
            body = openadk.MotionsOperation(motion=motion, operation=operation, timestamp=int(time.time()))  # MotionsOperation | 运动控制的参数
            try:
                # 运动控制
                api_response = self.api_instance.put_motions(body)
                print(api_response)
                self.assertEqual(0, api_response.code)
                self.assertNotEqual(None, api_response.data)
            except ApiException as e:
                print("Exception when calling MotionsApi->put_motions: %s\n" % e)


if __name__ == '__main__':
    unittest.main()
