# coding: utf-8

"""
    Yanshee RESTful API

    Yanshee RESTful APIs是一套专门为编程爱好者提供二次开发的接口．它通过http/https的方式向外界提供机器人控制，传感器读取，机器人视觉等功能．用户还可以通过编程的方式训练自己的模型，学习一些机器学习的内容．  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: swenggroup@ubtrobot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openadk
from openadk.api.devices_api import DevicesApi  # noqa: E501
from openadk.rest import ApiException


class TestDevicesApi(unittest.TestCase):
    """DevicesApi unit test stubs"""

    def setUp(self):
        self.api = openadk.api.devices_api.DevicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_devices_battery(self):
        """Test case for get_devices_battery

        获得机器人电量信息  # noqa: E501
        """
        pass

    def test_get_devices_fall_management(self):
        """Test case for get_devices_fall_management

        获得机器人摔倒管理状态  # noqa: E501
        """
        pass

    def test_get_devices_languages(self):
        """Test case for get_devices_languages

        获得机器人语言信息  # noqa: E501
        """
        pass

    def test_get_devices_led(self):
        """Test case for get_devices_led

        获取机器人灯效  # noqa: E501
        """
        pass

    def test_get_devices_versions(self):
        """Test case for get_devices_versions

        获得机器人版本信息  # noqa: E501
        """
        pass

    def test_get_devices_volume(self):
        """Test case for get_devices_volume

        获得机器人音量  # noqa: E501
        """
        pass

    def test_put_devices_fall_management(self):
        """Test case for put_devices_fall_management

        设置机器人摔倒管理状态  # noqa: E501
        """
        pass

    def test_put_devices_languages(self):
        """Test case for put_devices_languages

        设置机器人语言  # noqa: E501
        """
        pass

    def test_put_devices_led(self):
        """Test case for put_devices_led

        设置机器人灯效  # noqa: E501
        """
        pass

    def test_put_devices_volume(self):
        """Test case for put_devices_volume

        设置机器人音量  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
