# coding: utf-8

"""
    Yanshee RESTful API

    Yanshee RESTful APIs是一套专门为编程爱好者提供二次开发的接口．它通过http/https的方式向外界提供机器人控制，传感器读取，机器人视觉等功能．用户还可以通过编程的方式训练自己的模型，学习一些机器学习的内容．  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: swenggroup@ubtrobot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openadk
from openadk.api.sensors_api import SensorsApi  # noqa: E501
from openadk.rest import ApiException


class TestSensorsApi(unittest.TestCase):
    """SensorsApi unit test stubs"""

    def setUp(self):
        self.api = openadk.api.sensors_api.SensorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_sensors_environment(self):
        """Test case for get_sensors_environment

        获取环境传感器值  # noqa: E501
        """
        pass

    def test_get_sensors_gyro(self):
        """Test case for get_sensors_gyro

        获取运动传感器值  # noqa: E501
        """
        pass

    def test_get_sensors_infrared(self):
        """Test case for get_sensors_infrared

        获取红外传感器值  # noqa: E501
        """
        pass

    def test_get_sensors_list(self):
        """Test case for get_sensors_list

        获取所有传感器的列表。  # noqa: E501
        """
        pass

    def test_get_sensors_pressure(self):
        """Test case for get_sensors_pressure

        获取压力传感器值  # noqa: E501
        """
        pass

    def test_get_sensors_touch(self):
        """Test case for get_sensors_touch

        获取触摸传感器值  # noqa: E501
        """
        pass

    def test_get_sensors_ultrasonic(self):
        """Test case for get_sensors_ultrasonic

        获取超声传感器值  # noqa: E501
        """
        pass

    def test_put_sensors(self):
        """Test case for put_sensors

        传感器设置（校准或修改地址）  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
