# coding: utf-8

"""
    Yanshee RESTful API

    Yanshee RESTful APIs是一套专门为编程爱好者提供二次开发的接口．它通过http/https的方式向外界提供机器人控制，传感器读取，机器人视觉等功能．用户还可以通过编程的方式训练自己的模型，学习一些机器学习的内容．  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: swenggroup@ubtrobot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openadk
from openadk.api.voice_api import VoiceApi  # noqa: E501
from openadk.rest import ApiException


class TestVoiceApi(unittest.TestCase):
    """VoiceApi unit test stubs"""

    def setUp(self):
        self.api = openadk.api.voice_api.VoiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_voice_asr(self):
        """Test case for delete_voice_asr

        停止语义理解  # noqa: E501
        """
        pass

    def test_delete_voice_iat(self):
        """Test case for delete_voice_iat

        停止语音识别  # noqa: E501
        """
        pass

    def test_delete_voice_tts(self):
        """Test case for delete_voice_tts

        停止当前播放的tts语音  # noqa: E501
        """
        pass

    def test_get_voice_asr(self):
        """Test case for get_voice_asr

        获取语义理解工作状态  # noqa: E501
        """
        pass

    def test_get_voice_iat(self):
        """Test case for get_voice_iat

        获取语音识别工作状态  # noqa: E501
        """
        pass

    def test_get_voice_tts(self):
        """Test case for get_voice_tts

        获取当前tts工作状态  # noqa: E501
        """
        pass

    def test_put_voice_asr(self):
        """Test case for put_voice_asr

        开始语义理解  # noqa: E501
        """
        pass

    def test_put_voice_iat(self):
        """Test case for put_voice_iat

        开始语音识别  # noqa: E501
        """
        pass

    def test_put_voice_tts(self):
        """Test case for put_voice_tts

        开始tts任务  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
