# coding: utf-8

"""
    Yanshee RESTful API

    Yanshee RESTful APIs是一套专门为编程爱好者提供二次开发的接口．它通过http/https的方式向外界提供机器人控制，传感器读取，机器人视觉等功能．用户还可以通过编程的方式训练自己的模型，学习一些机器学习的内容．  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: swenggroup@ubtrobot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openadk
from openadk.models.motions_parameter import MotionsParameter  # noqa: E501
from openadk.rest import ApiException


class TestMotionsParameter(unittest.TestCase):
    """MotionsParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMotionsParameter(self):
        """Test MotionsParameter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openadk.models.motions_parameter.MotionsParameter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
