# coding: utf-8

"""
    Yanshee RESTful API

     ## Overview Yanshee RESTful APIs are generated by the [swagger-codegen](https://github.com/swagger-api/swagger-codegen) project. By using the [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki) from a remote server. The API service uses the [Connexion](https://github.com/zalando/connexion) library on top of Flask.  To provide the API service, Yanshee RESTful APIs are integrated into apollo package, it is a part of Yanshee-ROS framework. Yanshee RESTful APIs provided two language versions: - [English version](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [Chinese version](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## Requirements. Python 2.7 or 3.4+  ## Getting Started Please follow the [installation procedure](#installation--usage) and then run the following:  ``` from __future__ import print_function import time import openadk from openadk.rest import ApiException from pprint import pprint  # create an instance of the API class configuration = openadk.Configuration() configuration.host = 'http://192.168.1.100:9090/v1' api_instance = openadk.DevicesApi(openadk.ApiClient(configuration)) try:  # Get system's battery information  api_response = api_instance.get_devices_battery()  pprint(api_response) except ApiException as e:  print(\"Exception when calling DevicesApi->get_devices_battery: %s\" % e)  ```   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: swenggroup@ubtrobot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
import sys
from setuptools import setup, find_packages

NAME = "openadk"
VERSION = "1.0.0"

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
	"connexion", 
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]

setup(
    name=NAME,
    version=VERSION,
    description="Yanshee Open ADK",
    author_email="swenggroup@ubtrobot.com",
    url="",
    keywords=["Swagger", "Yanshee Open ADK"],
    install_requires=REQUIRES,
    packages=find_packages(),
    package_data={'': ['swagger/swagger.yaml']},
    include_package_data=True,
    entry_points={
        'console_scripts': ['openadk=openadk.__main__:main']},
    long_description="""\
     ## Overview Open ADK is designed for the users that they can build their own application very quickly. Open ADK provided two features: - Easy way to call API. - Easy way to receive the data from remote device.  This Python package is automatically generated by the Swagger Codegen project: - API version: 1.0.0 - Package version: 1.0.0 ## Requirements. Python 2.7 or 3.4+ ## Installation &amp; Usage You can install Open ADK from github. &#x60;&#x60;&#x60; pip install git+https://github.com/UBTEDU/Yanshee_OpenADK.git &#x60;&#x60;&#x60; (you may need to run pip with root permission: sudo pip install git+https://github.com//.git) Then import the package: &#x60;&#x60;&#x60; import openadk &#x60;&#x60;&#x60; ## Setuptools Install via [Setuptools](https://pypi.org/project/setuptools/). &#x60;&#x60;&#x60; python setup.py install --user &#x60;&#x60;&#x60; (or sudo python setup.py install to install the package for all users) Then import the package: &#x60;&#x60;&#x60; import openadk &#x60;&#x60;&#x60; ## Getting Started Please follow the installation procedure and then run the following: &#x60;&#x60;&#x60; from __future__ import print_function import time import openadk from openadk.rest import ApiException from pprint import pprint  # create an instance of the API class configuration &#x3D; openadk.Configuration() configuration.host &#x3D; &#39;http://&lt;ip&gt;:9090/v1&#39; api_instance &#x3D; openadk.DevicesApi(openadk.ApiClient(configuration))  try:  # Get system&#39;s battery information  api_response &#x3D; api_instance.get_devices_battery()  pprint(api_response) except ApiException as e:  print(\&quot;Exception when calling DevicesApi-&gt;get_devices_battery: %s \&quot; % e) &#x60;&#x60;&#x60; 
    """
)

