# coding: utf-8

"""
    Yanshee RESTful API

    Yanshee RESTful APIs是一套专门为编程爱好者提供二次开发的接口．它通过http/https的方式向外界提供机器人控制，传感器读取，机器人视觉等功能．用户还可以通过编程的方式训练自己的模型，学习一些机器学习的内容．  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: swenggroup@ubtrobot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DevicesVersions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'core': 'str',
        'servo': 'str'
    }

    attribute_map = {
        'core': 'core',
        'servo': 'servo'
    }

    def __init__(self, core=None, servo=None):  # noqa: E501
        """DevicesVersions - a model defined in Swagger"""  # noqa: E501

        self._core = None
        self._servo = None
        self.discriminator = None

        if core is not None:
            self.core = core
        if servo is not None:
            self.servo = servo

    @property
    def core(self):
        """Gets the core of this DevicesVersions.  # noqa: E501


        :return: The core of this DevicesVersions.  # noqa: E501
        :rtype: str
        """
        return self._core

    @core.setter
    def core(self, core):
        """Sets the core of this DevicesVersions.


        :param core: The core of this DevicesVersions.  # noqa: E501
        :type: str
        """

        self._core = core

    @property
    def servo(self):
        """Gets the servo of this DevicesVersions.  # noqa: E501


        :return: The servo of this DevicesVersions.  # noqa: E501
        :rtype: str
        """
        return self._servo

    @servo.setter
    def servo(self, servo):
        """Sets the servo of this DevicesVersions.


        :param servo: The servo of this DevicesVersions.  # noqa: E501
        :type: str
        """

        self._servo = servo

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DevicesVersions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DevicesVersions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
