# coding: utf-8

"""
    Yanshee RESTful API

     ## Overview Yanshee RESTful APIs are generated by the [swagger-codegen](https://github.com/swagger-api/swagger-codegen) project. By using the [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki) from a remote server. The API service uses the [Connexion](https://github.com/zalando/connexion) library on top of Flask.  To provide the API service, Yanshee RESTful APIs are integrated into apollo package, it is a part of Yanshee-ROS framework. Yanshee RESTful APIs provided two language versions: - [English version](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [Chinese version](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## Requirements. Python 2.7 or 3.4+  ## Getting Started Please follow the [installation procedure](#installation--usage) and then run the following:  ``` from __future__ import print_function import time import openadk from openadk.rest import ApiException from pprint import pprint  # create an instance of the API class configuration = openadk.Configuration() configuration.host = 'http://192.168.1.100:9090/v1' api_instance = openadk.DevicesApi(openadk.ApiClient(configuration)) try:  # Get system's battery information  api_response = api_instance.get_devices_battery()  pprint(api_response) except ApiException as e:  print(\"Exception when calling DevicesApi->get_devices_battery: %s\" % e)  ```   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: swenggroup@ubtrobot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DevicesBattery(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'voltage': 'int',
        'charging': 'int',
        'percent': 'int'
    }

    attribute_map = {
        'voltage': 'voltage',
        'charging': 'charging',
        'percent': 'percent'
    }

    def __init__(self, voltage=None, charging=None, percent=None):  # noqa: E501
        """DevicesBattery - a model defined in Swagger"""  # noqa: E501

        self._voltage = None
        self._charging = None
        self._percent = None
        self.discriminator = None

        self.voltage = voltage
        self.charging = charging
        self.percent = percent

    @property
    def voltage(self):
        """Gets the voltage of this DevicesBattery.  # noqa: E501

        Battery voltage (mV)  # noqa: E501

        :return: The voltage of this DevicesBattery.  # noqa: E501
        :rtype: int
        """
        return self._voltage

    @voltage.setter
    def voltage(self, voltage):
        """Sets the voltage of this DevicesBattery.

        Battery voltage (mV)  # noqa: E501

        :param voltage: The voltage of this DevicesBattery.  # noqa: E501
        :type: int
        """
        if voltage is None:
            raise ValueError("Invalid value for `voltage`, must not be `None`")  # noqa: E501

        self._voltage = voltage

    @property
    def charging(self):
        """Gets the charging of this DevicesBattery.  # noqa: E501

         Charging status - 1 Charging - 0 Not charging   # noqa: E501

        :return: The charging of this DevicesBattery.  # noqa: E501
        :rtype: int
        """
        return self._charging

    @charging.setter
    def charging(self, charging):
        """Sets the charging of this DevicesBattery.

         Charging status - 1 Charging - 0 Not charging   # noqa: E501

        :param charging: The charging of this DevicesBattery.  # noqa: E501
        :type: int
        """
        if charging is None:
            raise ValueError("Invalid value for `charging`, must not be `None`")  # noqa: E501

        self._charging = charging

    @property
    def percent(self):
        """Gets the percent of this DevicesBattery.  # noqa: E501

        Battery percentage  # noqa: E501

        :return: The percent of this DevicesBattery.  # noqa: E501
        :rtype: int
        """
        return self._percent

    @percent.setter
    def percent(self, percent):
        """Sets the percent of this DevicesBattery.

        Battery percentage  # noqa: E501

        :param percent: The percent of this DevicesBattery.  # noqa: E501
        :type: int
        """
        if percent is None:
            raise ValueError("Invalid value for `percent`, must not be `None`")  # noqa: E501

        self._percent = percent

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DevicesBattery, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DevicesBattery):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
