# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openadk.models.base_model_ import Model
from openadk.models.name import Name  # noqa: F401,E501
from openadk import util


class MediaMusicList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, music=None):  # noqa: E501
        """MediaMusicList - a model defined in Swagger

        :param music: The music of this MediaMusicList.  # noqa: E501
        :type music: List[Name]
        """
        self.swagger_types = {
            'music': List[Name]
        }

        self.attribute_map = {
            'music': 'music'
        }

        self._music = music

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MediaMusicList of this MediaMusicList.  # noqa: E501
        :rtype: MediaMusicList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def music(self):
        """Gets the music of this MediaMusicList.


        :return: The music of this MediaMusicList.
        :rtype: List[Name]
        """
        return self._music

    @music.setter
    def music(self, music):
        """Sets the music of this MediaMusicList.


        :param music: The music of this MediaMusicList.
        :type music: List[Name]
        """

        self._music = music
