# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openadk.models.base_model_ import Model
from openadk import util


class MediaMusicStatusResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, status=None, name='none'):  # noqa: E501
        """MediaMusicStatusResponse - a model defined in Swagger

        :param status: The status of this MediaMusicStatusResponse.  # noqa: E501
        :type status: str
        :param name: The name of this MediaMusicStatusResponse.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'status': str,
            'name': str
        }

        self.attribute_map = {
            'status': 'status',
            'name': 'name'
        }

        self._status = status
        self._name = name

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MediaMusicStatusResponse of this MediaMusicStatusResponse.  # noqa: E501
        :rtype: MediaMusicStatusResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self):
        """Gets the status of this MediaMusicStatusResponse.

        动作运行状态  # noqa: E501

        :return: The status of this MediaMusicStatusResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this MediaMusicStatusResponse.

        动作运行状态  # noqa: E501

        :param status: The status of this MediaMusicStatusResponse.
        :type status: str
        """
        allowed_values = ["idle", "running", "pause"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def name(self):
        """Gets the name of this MediaMusicStatusResponse.

        动作名  # noqa: E501

        :return: The name of this MediaMusicStatusResponse.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MediaMusicStatusResponse.

        动作名  # noqa: E501

        :param name: The name of this MediaMusicStatusResponse.
        :type name: str
        """

        self._name = name
