# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openadk.models.base_model_ import Model
from openadk.models.motions_info import MotionsInfo  # noqa: F401,E501
from openadk import util


class MotionsList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, motions=None):  # noqa: E501
        """MotionsList - a model defined in Swagger

        :param motions: The motions of this MotionsList.  # noqa: E501
        :type motions: List[MotionsInfo]
        """
        self.swagger_types = {
            'motions': List[MotionsInfo]
        }

        self.attribute_map = {
            'motions': 'motions'
        }

        self._motions = motions

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MotionsList of this MotionsList.  # noqa: E501
        :rtype: MotionsList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def motions(self):
        """Gets the motions of this MotionsList.


        :return: The motions of this MotionsList.
        :rtype: List[MotionsInfo]
        """
        return self._motions

    @motions.setter
    def motions(self, motions):
        """Sets the motions of this MotionsList.


        :param motions: The motions of this MotionsList.
        :type motions: List[MotionsInfo]
        """
        if motions is None:
            raise ValueError("Invalid value for `motions`, must not be `None`")  # noqa: E501

        self._motions = motions
