# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openadk.models.base_model_ import Model
from openadk import util


class RunStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, status=None, timestamp=None):  # noqa: E501
        """RunStatus - a model defined in Swagger

        :param status: The status of this RunStatus.  # noqa: E501
        :type status: str
        :param timestamp: The timestamp of this RunStatus.  # noqa: E501
        :type timestamp: int
        """
        self.swagger_types = {
            'status': str,
            'timestamp': int
        }

        self.attribute_map = {
            'status': 'status',
            'timestamp': 'timestamp'
        }

        self._status = status
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RunStatus of this RunStatus.  # noqa: E501
        :rtype: RunStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self):
        """Gets the status of this RunStatus.


        :return: The status of this RunStatus.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this RunStatus.


        :param status: The status of this RunStatus.
        :type status: str
        """
        allowed_values = ["idle", "running", "pause"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def timestamp(self):
        """Gets the timestamp of this RunStatus.

        时间戳, Unix标准时间  # noqa: E501

        :return: The timestamp of this RunStatus.
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this RunStatus.

        时间戳, Unix标准时间  # noqa: E501

        :param timestamp: The timestamp of this RunStatus.
        :type timestamp: int
        """

        self._timestamp = timestamp
