# coding: utf-8

"""
    Yanshee RESTful API

    Yanshee RESTful APIs是一套专门为编程爱好者提供二次开发的接口．它通过http/https的方式向外界提供机器人控制，传感器读取，机器人视觉等功能．用户还可以通过编程的方式训练自己的模型，学习一些机器学习的内容．  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: swenggroup@ubtrobot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SensorsParameter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'id': 'int',
        'value': 'int'
    }

    attribute_map = {
        'type': 'type',
        'id': 'id',
        'value': 'value'
    }

    def __init__(self, type='gyro', id=None, value=None):  # noqa: E501
        """SensorsParameter - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._id = None
        self._value = None
        self.discriminator = None

        self.type = type
        self.id = id
        if value is not None:
            self.value = value

    @property
    def type(self):
        """Gets the type of this SensorsParameter.  # noqa: E501

         传感器类型，取值说明： - gyro  （陀螺仪） - infrared  （红外测距传感器） - ultrasonic  （超声测距传感器） - touch  （触摸传感器） - pressure （压力传感器）    # noqa: E501

        :return: The type of this SensorsParameter.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SensorsParameter.

         传感器类型，取值说明： - gyro  （陀螺仪） - infrared  （红外测距传感器） - ultrasonic  （超声测距传感器） - touch  （触摸传感器） - pressure （压力传感器）    # noqa: E501

        :param type: The type of this SensorsParameter.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["gyro", "infrared", "ultrasonic", "touch", "pressure"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def id(self):
        """Gets the id of this SensorsParameter.  # noqa: E501


        :return: The id of this SensorsParameter.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SensorsParameter.


        :param id: The id of this SensorsParameter.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if id is not None and id > 127:  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a value less than or equal to `127`")  # noqa: E501
        if id is not None and id < 1:  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a value greater than or equal to `1`")  # noqa: E501

        self._id = id

    @property
    def value(self):
        """Gets the value of this SensorsParameter.  # noqa: E501

         当operation为 modify 时，取值说明： - 17~22 （传感器的类型为超声时） - 23~28 （传感器的类型为红外时） - 29~34 （传感器的类型为触摸时） - 35~40 （传感器的类型为压力时）  注意：其它类型的传感器不允许修改地址! 另外，当传感器的列表中存在slot字段时此功能不可用！  当operation为 calibrate 时，省略该字段；  # noqa: E501

        :return: The value of this SensorsParameter.  # noqa: E501
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this SensorsParameter.

         当operation为 modify 时，取值说明： - 17~22 （传感器的类型为超声时） - 23~28 （传感器的类型为红外时） - 29~34 （传感器的类型为触摸时） - 35~40 （传感器的类型为压力时）  注意：其它类型的传感器不允许修改地址! 另外，当传感器的列表中存在slot字段时此功能不可用！  当operation为 calibrate 时，省略该字段；  # noqa: E501

        :param value: The value of this SensorsParameter.  # noqa: E501
        :type: int
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SensorsParameter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SensorsParameter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
