# coding: utf-8

"""
    Yanshee RESTful API

    Yanshee RESTful APIs是一套专门为编程爱好者提供二次开发的接口．它通过http/https的方式向外界提供机器人控制，传感器读取，机器人视觉等功能．用户还可以通过编程的方式训练自己的模型，学习一些机器学习的内容．  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: swenggroup@ubtrobot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from openadk.models.servos_angles import ServosAngles  # noqa: F401,E501


class ServosAnglesRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'runtime': 'int',
        'angles': 'ServosAngles'
    }

    attribute_map = {
        'runtime': 'runtime',
        'angles': 'angles'
    }

    def __init__(self, runtime=None, angles=None):  # noqa: E501
        """ServosAnglesRequest - a model defined in Swagger"""  # noqa: E501

        self._runtime = None
        self._angles = None
        self.discriminator = None

        if runtime is not None:
            self.runtime = runtime
        self.angles = angles

    @property
    def runtime(self):
        """Gets the runtime of this ServosAnglesRequest.  # noqa: E501

        运行时间，单位ms  # noqa: E501

        :return: The runtime of this ServosAnglesRequest.  # noqa: E501
        :rtype: int
        """
        return self._runtime

    @runtime.setter
    def runtime(self, runtime):
        """Sets the runtime of this ServosAnglesRequest.

        运行时间，单位ms  # noqa: E501

        :param runtime: The runtime of this ServosAnglesRequest.  # noqa: E501
        :type: int
        """
        if runtime is not None and runtime > 4000:  # noqa: E501
            raise ValueError("Invalid value for `runtime`, must be a value less than or equal to `4000`")  # noqa: E501
        if runtime is not None and runtime < 200:  # noqa: E501
            raise ValueError("Invalid value for `runtime`, must be a value greater than or equal to `200`")  # noqa: E501

        self._runtime = runtime

    @property
    def angles(self):
        """Gets the angles of this ServosAnglesRequest.  # noqa: E501


        :return: The angles of this ServosAnglesRequest.  # noqa: E501
        :rtype: ServosAngles
        """
        return self._angles

    @angles.setter
    def angles(self, angles):
        """Sets the angles of this ServosAnglesRequest.


        :param angles: The angles of this ServosAnglesRequest.  # noqa: E501
        :type: ServosAngles
        """
        if angles is None:
            raise ValueError("Invalid value for `angles`, must not be `None`")  # noqa: E501

        self._angles = angles

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServosAnglesRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServosAnglesRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
