# coding: utf-8

"""
    Yanshee RESTful API

    Yanshee RESTful APIs是一套专门为编程爱好者提供二次开发的接口．它通过http/https的方式向外界提供机器人控制，传感器读取，机器人视觉等功能．用户还可以通过编程的方式训练自己的模型，学习一些机器学习的内容．  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: swenggroup@ubtrobot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SubscriptionsSensors(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'id': 'int',
        'url': 'str',
        'timeout': 'int',
        'timeval': 'int'
    }

    attribute_map = {
        'type': 'type',
        'id': 'id',
        'url': 'url',
        'timeout': 'timeout',
        'timeval': 'timeval'
    }

    def __init__(self, type=None, id=None, url=None, timeout=10, timeval=1000):  # noqa: E501
        """SubscriptionsSensors - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._id = None
        self._url = None
        self._timeout = None
        self._timeval = None
        self.discriminator = None

        self.type = type
        if id is not None:
            self.id = id
        self.url = url
        if timeout is not None:
            self.timeout = timeout
        if timeval is not None:
            self.timeval = timeval

    @property
    def type(self):
        """Gets the type of this SubscriptionsSensors.  # noqa: E501

        传感器类型  # noqa: E501

        :return: The type of this SubscriptionsSensors.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SubscriptionsSensors.

        传感器类型  # noqa: E501

        :param type: The type of this SubscriptionsSensors.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["gyro", "ultrasonic", "environment", "infrared", "touch", "pressure"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def id(self):
        """Gets the id of this SubscriptionsSensors.  # noqa: E501

        传感器ID，可不填  # noqa: E501

        :return: The id of this SubscriptionsSensors.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SubscriptionsSensors.

        传感器ID，可不填  # noqa: E501

        :param id: The id of this SubscriptionsSensors.  # noqa: E501
        :type: int
        """
        if id is not None and id > 126:  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a value less than or equal to `126`")  # noqa: E501
        if id is not None and id < 1:  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a value greater than or equal to `1`")  # noqa: E501

        self._id = id

    @property
    def url(self):
        """Gets the url of this SubscriptionsSensors.  # noqa: E501

        接口信息  # noqa: E501

        :return: The url of this SubscriptionsSensors.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this SubscriptionsSensors.

        接口信息  # noqa: E501

        :param url: The url of this SubscriptionsSensors.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def timeout(self):
        """Gets the timeout of this SubscriptionsSensors.  # noqa: E501

        超时停止发送的时间  # noqa: E501

        :return: The timeout of this SubscriptionsSensors.  # noqa: E501
        :rtype: int
        """
        return self._timeout

    @timeout.setter
    def timeout(self, timeout):
        """Sets the timeout of this SubscriptionsSensors.

        超时停止发送的时间  # noqa: E501

        :param timeout: The timeout of this SubscriptionsSensors.  # noqa: E501
        :type: int
        """
        if timeout is not None and timeout > 60:  # noqa: E501
            raise ValueError("Invalid value for `timeout`, must be a value less than or equal to `60`")  # noqa: E501
        if timeout is not None and timeout < 1:  # noqa: E501
            raise ValueError("Invalid value for `timeout`, must be a value greater than or equal to `1`")  # noqa: E501

        self._timeout = timeout

    @property
    def timeval(self):
        """Gets the timeval of this SubscriptionsSensors.  # noqa: E501

        上报的最短时间间隔，单位ms（豪秒）  # noqa: E501

        :return: The timeval of this SubscriptionsSensors.  # noqa: E501
        :rtype: int
        """
        return self._timeval

    @timeval.setter
    def timeval(self, timeval):
        """Sets the timeval of this SubscriptionsSensors.

        上报的最短时间间隔，单位ms（豪秒）  # noqa: E501

        :param timeval: The timeval of this SubscriptionsSensors.  # noqa: E501
        :type: int
        """
        if timeval is not None and timeval > 5000:  # noqa: E501
            raise ValueError("Invalid value for `timeval`, must be a value less than or equal to `5000`")  # noqa: E501
        if timeval is not None and timeval < 100:  # noqa: E501
            raise ValueError("Invalid value for `timeval`, must be a value greater than or equal to `100`")  # noqa: E501

        self._timeval = timeval

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubscriptionsSensors, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubscriptionsSensors):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
