# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openadk.models.base_model_ import Model
from openadk.models.subscription_sensors_pressure_value import SubscriptionSensorsPressureValue  # noqa: F401,E501
from openadk import util


class SubscriptionSensorsPressureValueResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code=None, data=None, msg=None):  # noqa: E501
        """SubscriptionSensorsPressureValueResponse - a model defined in Swagger

        :param code: The code of this SubscriptionSensorsPressureValueResponse.  # noqa: E501
        :type code: int
        :param data: The data of this SubscriptionSensorsPressureValueResponse.  # noqa: E501
        :type data: SubscriptionSensorsPressureValue
        :param msg: The msg of this SubscriptionSensorsPressureValueResponse.  # noqa: E501
        :type msg: str
        """
        self.swagger_types = {
            'code': int,
            'data': SubscriptionSensorsPressureValue,
            'msg': str
        }

        self.attribute_map = {
            'code': 'code',
            'data': 'data',
            'msg': 'msg'
        }

        self._code = code
        self._data = data
        self._msg = msg

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubscriptionSensorsPressureValueResponse of this SubscriptionSensorsPressureValueResponse.  # noqa: E501
        :rtype: SubscriptionSensorsPressureValueResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this SubscriptionSensorsPressureValueResponse.

        返回码，0表示正常  # noqa: E501

        :return: The code of this SubscriptionSensorsPressureValueResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this SubscriptionSensorsPressureValueResponse.

        返回码，0表示正常  # noqa: E501

        :param code: The code of this SubscriptionSensorsPressureValueResponse.
        :type code: int
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def data(self):
        """Gets the data of this SubscriptionSensorsPressureValueResponse.


        :return: The data of this SubscriptionSensorsPressureValueResponse.
        :rtype: SubscriptionSensorsPressureValue
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this SubscriptionSensorsPressureValueResponse.


        :param data: The data of this SubscriptionSensorsPressureValueResponse.
        :type data: SubscriptionSensorsPressureValue
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def msg(self):
        """Gets the msg of this SubscriptionSensorsPressureValueResponse.

        提示信息  # noqa: E501

        :return: The msg of this SubscriptionSensorsPressureValueResponse.
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg):
        """Sets the msg of this SubscriptionSensorsPressureValueResponse.

        提示信息  # noqa: E501

        :param msg: The msg of this SubscriptionSensorsPressureValueResponse.
        :type msg: str
        """
        if msg is None:
            raise ValueError("Invalid value for `msg`, must not be `None`")  # noqa: E501

        self._msg = msg
