# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openadk.models.base_model_ import Model
from openadk.models.subscription_sensors_pressure_info import SubscriptionSensorsPressureInfo  # noqa: F401,E501
from openadk import util


class SubscriptionSensorsPressureValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, pressure=None):  # noqa: E501
        """SubscriptionSensorsPressureValue - a model defined in Swagger

        :param pressure: The pressure of this SubscriptionSensorsPressureValue.  # noqa: E501
        :type pressure: List[SubscriptionSensorsPressureInfo]
        """
        self.swagger_types = {
            'pressure': List[SubscriptionSensorsPressureInfo]
        }

        self.attribute_map = {
            'pressure': 'pressure'
        }

        self._pressure = pressure

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubscriptionSensorsPressureValue of this SubscriptionSensorsPressureValue.  # noqa: E501
        :rtype: SubscriptionSensorsPressureValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pressure(self):
        """Gets the pressure of this SubscriptionSensorsPressureValue.


        :return: The pressure of this SubscriptionSensorsPressureValue.
        :rtype: List[SubscriptionSensorsPressureInfo]
        """
        return self._pressure

    @pressure.setter
    def pressure(self, pressure):
        """Sets the pressure of this SubscriptionSensorsPressureValue.


        :param pressure: The pressure of this SubscriptionSensorsPressureValue.
        :type pressure: List[SubscriptionSensorsPressureInfo]
        """
        if pressure is None:
            raise ValueError("Invalid value for `pressure`, must not be `None`")  # noqa: E501

        self._pressure = pressure
