# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openadk.models.base_model_ import Model
from openadk import util


class TotalTime(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, total_time=None):  # noqa: E501
        """TotalTime - a model defined in Swagger

        :param total_time: The total_time of this TotalTime.  # noqa: E501
        :type total_time: int
        """
        self.swagger_types = {
            'total_time': int
        }

        self.attribute_map = {
            'total_time': 'total_time'
        }

        self._total_time = total_time

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TotalTime of this TotalTime.  # noqa: E501
        :rtype: TotalTime
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total_time(self):
        """Gets the total_time of this TotalTime.

        运行完成需要的时间（单位ms）  # noqa: E501

        :return: The total_time of this TotalTime.
        :rtype: int
        """
        return self._total_time

    @total_time.setter
    def total_time(self, total_time):
        """Sets the total_time of this TotalTime.

        运行完成需要的时间（单位ms）  # noqa: E501

        :param total_time: The total_time of this TotalTime.
        :type total_time: int
        """

        self._total_time = total_time
