# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openadk.models.base_model_ import Model
from openadk import util


class VisionsPutResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code=None, timestamp=None, data=None, msg=None):  # noqa: E501
        """VisionsPutResponse - a model defined in Swagger

        :param code: The code of this VisionsPutResponse.  # noqa: E501
        :type code: int
        :param timestamp: The timestamp of this VisionsPutResponse.  # noqa: E501
        :type timestamp: int
        :param data: The data of this VisionsPutResponse.  # noqa: E501
        :type data: object
        :param msg: The msg of this VisionsPutResponse.  # noqa: E501
        :type msg: str
        """
        self.swagger_types = {
            'code': int,
            'timestamp': int,
            'data': object,
            'msg': str
        }

        self.attribute_map = {
            'code': 'code',
            'timestamp': 'timestamp',
            'data': 'data',
            'msg': 'msg'
        }

        self._code = code
        self._timestamp = timestamp
        self._data = data
        self._msg = msg

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VisionsPutResponse of this VisionsPutResponse.  # noqa: E501
        :rtype: VisionsPutResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this VisionsPutResponse.

        错误码  # noqa: E501

        :return: The code of this VisionsPutResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this VisionsPutResponse.

        错误码  # noqa: E501

        :param code: The code of this VisionsPutResponse.
        :type code: int
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def timestamp(self):
        """Gets the timestamp of this VisionsPutResponse.

        视觉任务时间戳  # noqa: E501

        :return: The timestamp of this VisionsPutResponse.
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this VisionsPutResponse.

        视觉任务时间戳  # noqa: E501

        :param timestamp: The timestamp of this VisionsPutResponse.
        :type timestamp: int
        """

        self._timestamp = timestamp

    @property
    def data(self):
        """Gets the data of this VisionsPutResponse.


        :return: The data of this VisionsPutResponse.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this VisionsPutResponse.


        :param data: The data of this VisionsPutResponse.
        :type data: object
        """

        self._data = data

    @property
    def msg(self):
        """Gets the msg of this VisionsPutResponse.

        错误码消息  # noqa: E501

        :return: The msg of this VisionsPutResponse.
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg):
        """Sets the msg of this VisionsPutResponse.

        错误码消息  # noqa: E501

        :param msg: The msg of this VisionsPutResponse.
        :type msg: str
        """
        if msg is None:
            raise ValueError("Invalid value for `msg`, must not be `None`")  # noqa: E501

        self._msg = msg
