# coding: utf-8

"""
    Yanshee RESTful API

     ## Overview Yanshee RESTful APIs are generated by the [swagger-codegen](https://github.com/swagger-api/swagger-codegen) project. By using the [OpenAPI-Spec](https://github.com/swagger-api/swagger-core/wiki) from a remote server. The API service uses the [Connexion](https://github.com/zalando/connexion) library on top of Flask.  To provide the API service, Yanshee RESTful APIs are integrated into apollo package, it is a part of Yanshee-ROS framework. Yanshee RESTful APIs provided two language versions: - [English version](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_en/1.0.0) - [Chinese version](https://app.swaggerhub.com/apis-docs/UBTEDU/apollo_cn/1.0.0)  ## Requirements. Python 2.7 or 3.4+  ## Getting Started Please follow the [installation procedure](#installation--usage) and then run the following:  ``` from __future__ import print_function import time import openadk from openadk.rest import ApiException from pprint import pprint  # create an instance of the API class configuration = openadk.Configuration() configuration.host = 'http://192.168.1.100:9090/v1' api_instance = openadk.DevicesApi(openadk.ApiClient(configuration)) try:  # Get system's battery information  api_response = api_instance.get_devices_battery()  pprint(api_response) except ApiException as e:  print(\"Exception when calling DevicesApi->get_devices_battery: %s\" % e)  ```   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: swenggroup@ubtrobot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VisionsTask(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'operation': 'str',
        'option': 'str',
        'timestamp': 'int'
    }

    attribute_map = {
        'type': 'type',
        'operation': 'operation',
        'option': 'option',
        'timestamp': 'timestamp'
    }

    def __init__(self, type=None, operation=None, option=None, timestamp=None):  # noqa: E501
        """VisionsTask - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._operation = None
        self._option = None
        self._timestamp = None
        self.discriminator = None

        self.type = type
        self.operation = operation
        if option is not None:
            self.option = option
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def type(self):
        """Gets the type of this VisionsTask.  # noqa: E501

         Define the vision task type. The ranges should be in: - tracking - recognition - gender - age_group - quantity - color_detect - age - expression   # noqa: E501

        :return: The type of this VisionsTask.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this VisionsTask.

         Define the vision task type. The ranges should be in: - tracking - recognition - gender - age_group - quantity - color_detect - age - expression   # noqa: E501

        :param type: The type of this VisionsTask.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["tracking", "recognition", "gender", "age_group", "quantity", "color_detect", "age", "expression"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def operation(self):
        """Gets the operation of this VisionsTask.  # noqa: E501

         Define the vision task operation. The ranges should be in: - start - stop   # noqa: E501

        :return: The operation of this VisionsTask.  # noqa: E501
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this VisionsTask.

         Define the vision task operation. The ranges should be in: - start - stop   # noqa: E501

        :param operation: The operation of this VisionsTask.  # noqa: E501
        :type: str
        """
        if operation is None:
            raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501
        allowed_values = ["start", "stop"]  # noqa: E501
        if operation not in allowed_values:
            raise ValueError(
                "Invalid value for `operation` ({0}), must be one of {1}"  # noqa: E501
                .format(operation, allowed_values)
            )

        self._operation = operation

    @property
    def option(self):
        """Gets the option of this VisionsTask.  # noqa: E501

         Define the vision task option. The ranges should be in: - face - color - object  Constraint: If option is \"face\", type should be in : - tracking - recognition - quantity - age_group - gender - age - expression  If option is \"color\", type should be in : - color_detect If option is \"object\", type should be in : - recognition   # noqa: E501

        :return: The option of this VisionsTask.  # noqa: E501
        :rtype: str
        """
        return self._option

    @option.setter
    def option(self, option):
        """Sets the option of this VisionsTask.

         Define the vision task option. The ranges should be in: - face - color - object  Constraint: If option is \"face\", type should be in : - tracking - recognition - quantity - age_group - gender - age - expression  If option is \"color\", type should be in : - color_detect If option is \"object\", type should be in : - recognition   # noqa: E501

        :param option: The option of this VisionsTask.  # noqa: E501
        :type: str
        """
        allowed_values = ["face", "color", "object"]  # noqa: E501
        if option not in allowed_values:
            raise ValueError(
                "Invalid value for `option` ({0}), must be one of {1}"  # noqa: E501
                .format(option, allowed_values)
            )

        self._option = option

    @property
    def timestamp(self):
        """Gets the timestamp of this VisionsTask.  # noqa: E501

        The vision task timestamp.  # noqa: E501

        :return: The timestamp of this VisionsTask.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this VisionsTask.

        The vision task timestamp.  # noqa: E501

        :param timestamp: The timestamp of this VisionsTask.  # noqa: E501
        :type: int
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VisionsTask, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VisionsTask):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
