# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openadk.models.base_model_ import Model
from openadk.models.name import Name  # noqa: F401,E501
from openadk import util


class VoiceGetOfflineSyntaxGrammarsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, grammar=None):  # noqa: E501
        """VoiceGetOfflineSyntaxGrammarsResponse - a model defined in Swagger

        :param grammar: The grammar of this VoiceGetOfflineSyntaxGrammarsResponse.  # noqa: E501
        :type grammar: List[Name]
        """
        self.swagger_types = {
            'grammar': List[Name]
        }

        self.attribute_map = {
            'grammar': 'grammar'
        }

        self._grammar = grammar

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VoiceGetOfflineSyntaxGrammarsResponse of this VoiceGetOfflineSyntaxGrammarsResponse.  # noqa: E501
        :rtype: VoiceGetOfflineSyntaxGrammarsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def grammar(self):
        """Gets the grammar of this VoiceGetOfflineSyntaxGrammarsResponse.

        离线语法名称  # noqa: E501

        :return: The grammar of this VoiceGetOfflineSyntaxGrammarsResponse.
        :rtype: List[Name]
        """
        return self._grammar

    @grammar.setter
    def grammar(self, grammar):
        """Sets the grammar of this VoiceGetOfflineSyntaxGrammarsResponse.

        离线语法名称  # noqa: E501

        :param grammar: The grammar of this VoiceGetOfflineSyntaxGrammarsResponse.
        :type grammar: List[Name]
        """
        if grammar is None:
            raise ValueError("Invalid value for `grammar`, must not be `None`")  # noqa: E501

        self._grammar = grammar
